name: Rust Web

on:
  push:
    branches:
      - master

# Required for Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Checkout Repository"
        run: |
          mv ./web/* ./
          rm -rf ./web

      - name: "Cache Rust dependencies"
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"

      - name: "Set up Rust"
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup toolchain install stable
          rustup target add wasm32-unknown-unknown

      - name: "Build Dioxus Project 🎁"
        shell: bash
        run: |
          source $HOME/.cargo/env
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall dioxus-cli -y
          dx build --release

      - name: "Upload Pages artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/dx/my-website/release/web/public

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to GitHub Pages 🚀"
        id: deployment
        uses: actions/deploy-pages@v4
